### ISSUE TITLE
Migrate from feature sets by directory structure to feature flags in make command

### ISSUE THREAD

**Issue by sadekbaroudi** [sadekbaroudi/qmk_firmware#7]
Changing then way I do firmware... no more subdirectories for building firmware... instead of this:
make fingerpunch/ffkb_byomcu/rgblight_cirque_ec11:default

It'll be something like this:
make fingerpunch/ffkb_byomcu:default RGBLIGHT_ENABLE=yes CIRQUE_ENABLE=yes EC11=yes

**Comment by ridingintraffic** [comment]
are you going to add info.json files as well?  
it was a "breaking change" in the latest release of qmk
https://github.com/qmk/qmk_firmware/commit/7222969964a41a295910844ef93372e368439a09

**Comment by sadekbaroudi** [comment]
> are you going to add info.json files as well? it was a "breaking change" in the latest release of qmk [qmk@7222969](https://github.com/qmk/qmk_firmware/commit/7222969964a41a295910844ef93372e368439a09)

Yeah, I need to do that as well...

**Comment by sadekbaroudi** [comment]
https://github.com/sadekbaroudi/qmk_firmware/pull/8
